# -*- coding: utf-8 -*-
# ==================================================================================================================================
# Copyright (c) 2017 - 2018 Stephen Copplestone and Matthias Sonntag
#
# This file is part of reggie (github.com/reggie-framework/reggie). reggie is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3
# of the License, or (at your option) any later version.
#
# reggie is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty
# of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License v3.0 for more details.
#
# You should have received a copy of the GNU General Public License along with reggie. If not, see <http://www.gnu.org/licenses/>.
# ==================================================================================================================================

# Workflow for continuous integration (CI)
name: CI

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - master
      - main
  # Runs on pull requests
  pull_request:
  # Allows running this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      # note that these default values are only set when creating a workflow by hand on github, therfore the default values are also hardcoded below
      testcase_dir_build:
        # testcase directory used for building the executable with reggie
        default: 'CHE_maxwell'
      testcase_dir:
        # this testcase directory is used for the execution with the pre-compiled executable, note that it might contain more than one testcase, use $TESTCASE to specify a single on (for shorter runtime)
        default: 'NIG_Reservoir_single_core'
      testcase:
        # this testcase includes multiple cores for the reggie execution
        default: 'RELAX_N2'

# Permissions
permissions:
  contents:  read        # default for all jobs
  packages:  read

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued
concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

# Environment variables
env:
  UV_LINK_MODE: copy

jobs:
# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Setup
# ----------------------------------------------------------------------------------------------------------------------------------------------------
  venv:
    name: Setup venv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v5
        id: cache
        with:
          path: .venv
          key: venv-${{ hashFiles('pyproject.toml') }}
      - name: Create virtual environment
        if: steps.cache.outputs.cache-hit != 'true'
        shell: bash
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install ruff ty vulture
          python -m pip install --editable .

  piclas:
    name: Clone piclas repository from github
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y libopenmpi-dev libhdf5-openmpi-dev hdf5-tools libopenblas-dev
      - uses: actions/cache@v5
        id: cache
        with:
          path: piclas
          key: piclas-${{ github.sha }}
      - name: Clone piclas from github
        if: steps.cache.outputs.cache-hit != 'true'
        shell: bash
        run: |
          git clone https://github.com/piclas-framework/piclas.git
          cd piclas
          mkdir build
          cd build
          # create executable with tools script
          export FFLAGS="-fPIC" CFLAGS="-fPIC" CXXFLAGS="-fPIC"
          ../tools/cmake-builds-ini.sh ../regressioncheck/${{ inputs.testcase_dir || 'NIG_Reservoir_single_core' }}/builds.ini

# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Linter
# ----------------------------------------------------------------------------------------------------------------------------------------------------
  ruff:
    name: Lint / ruff
    runs-on: ubuntu-latest
    needs: [venv]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v5
        with:
          path: .venv
          key: venv-${{ hashFiles('pyproject.toml') }}
      - name: Run ruff
        shell: bash
        run: |
          source .venv/bin/activate
          ruff --version
          ruff check --config pyproject.toml --preview reggie

  ty:
    name: Lint / ty
    runs-on: ubuntu-latest
    needs: [venv]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v5
        with:
          path: .venv
          key: venv-${{ hashFiles('pyproject.toml') }}
      - name: Run ty
        shell: bash
        run: |
          source .venv/bin/activate
          ty --version
          ty check --color always --project reggie

  vulture:
    name: Lint / vulture
    runs-on: ubuntu-latest
    needs: [venv]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v5
        with:
          path: .venv
          key: venv-${{ hashFiles('pyproject.toml') }}
      - name: Run vulture
        shell: bash
        run: |
          source .venv/bin/activate
          vulture --version
          vulture --config pyproject.toml reggie

# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Compatibility
# ----------------------------------------------------------------------------------------------------------------------------------------------------
  compatibility:
    name: Compatibility / Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    needs: [ruff, ty, vulture]
    strategy:
      fail-fast: false
      matrix:
        include:
          - { python-version: "3.10" }
          - { python-version: "3.11" }
          - { python-version: "3.12" }
          - { python-version: "3.13" }
          - { python-version: "3.14" }
    steps:
      - uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}
      - uses: actions/checkout@v5
      - name: Run compatibility tests
        shell: bash
        run: |
          # Virtual environment
          python -m venv .venv
          source .venv/bin/activate
          # Compatibility
          python -m pip install --editable .
          reggie --help

# ----------------------------------------------------------------------------------------------------------------------------------------------------
# Regressionchecks
# ----------------------------------------------------------------------------------------------------------------------------------------------------
  Analyze_checks_single:
    # these analyzes do not need any external tools
    name: Regressioncheck / ${{ matrix.check }}
    runs-on: ubuntu-latest
    needs: [venv]
    strategy:
      fail-fast: false
      matrix:
        check:
          - CHE_Analyze_L2
          - CHE_Analyze_L2_file
          - CHE_Analyze_check_distribution
          - CHE_Analyze_check_hdf5
          - CHE_Analyze_compare_column
          - CHE_Analyze_compare_data_file
          - CHE_Analyze_integrate_line
          - CHE_Analyze_vtudiff
          - CHE_Analyze_Convtest_h
          - CHE_Analyze_Convtest_p
          - CHE_Analyze_Convtest_t
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v5
        with:
          path: .venv
          key: venv-${{ hashFiles('pyproject.toml') }}
      - name: Perform ${{ matrix.check }}
        shell: bash
        run: |
          source .venv/bin/activate
          reggie --dry-run regressioncheck/${{ matrix.check }}

  Analyze_checks_hdf5_tools:
    # these analyzes need the hdf5 toolset
    name: Regressioncheck (hdf5 tools) / ${{ matrix.check }}
    runs-on: ubuntu-latest
    needs: [venv]
    strategy:
      fail-fast: false
      matrix:
        check:
          - CHE_Analyze_h5diff
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v5
        with:
          path: .venv
          key: venv-${{ hashFiles('pyproject.toml') }}
      - name: Install HDF5 tools
        run: sudo apt-get install -y hdf5-tools
      - name: Perform ${{ matrix.check }}
        shell: bash
        run: |
          source .venv/bin/activate
          reggie --dry-run regressioncheck/${{ matrix.check }}

  Analyze_checks_piclas:
    # these analyzes need the piclas repo and executable
    name: Regressioncheck (with piclas builds) / ${{ matrix.check }}
    runs-on: ubuntu-latest
    needs: [venv, piclas]
    strategy:
      fail-fast: false
      matrix:
        include:
          - check: piclas/regressioncheck/${{ inputs.testcase_dir_build || 'CHE_maxwell' }}
            extra_args: ""                                          # no extra arguments, since reggie builds the executable itself
          - check: piclas/regressioncheck/${{ inputs.testcase_dir || 'NIG_Reservoir_single_core' }}/${{ inputs.testcase || 'RELAX_N2' }}
            extra_args: "--e piclas/build/bin/piclas"          # use pre-built executable
    steps:
      - uses: actions/checkout@v5
      - uses: actions/cache@v5
        with:
          path: .venv
          key: venv-${{ hashFiles('pyproject.toml') }}
      - uses: actions/cache@v5
        with:
          path: piclas
          key: piclas-${{ github.sha }}
      - name: Perform ${{ matrix.check }} ${{ matrix.extra_args }}
        shell: bash
        run: |
          source .venv/bin/activate
          reggie ${{ matrix.check }} ${{ matrix.extra_args }}